{"name": "test_login_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x00000284D5B11CA0>\n\n    def test_login_001(self):\n>       assert 0\nE       assert 0\n\ntest_login.py:4: AssertionError"}, "start": 1694583657411, "stop": 1694583657411, "uuid": "cbd91d72-e93e-4766-8894-f9affa6ff845", "historyId": "61fd03ca604429f4bd9d857ac5f51598", "testCaseId": "61fd03ca604429f4bd9d857ac5f51598", "fullName": "scripts.test_login.TestLogin#test_login_001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "renxiaoyan"}, {"name": "thread", "value": "3428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}