{"name": "test_login_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x000001C295333880>\n\n    def test_login_001(self):\n>       assert 0\nE       assert 0\n\ntest_login.py:4: AssertionError"}, "start": 1694583631798, "stop": 1694583631798, "uuid": "a371ad42-baa6-4024-803a-e7db9fb17cd1", "historyId": "61fd03ca604429f4bd9d857ac5f51598", "testCaseId": "61fd03ca604429f4bd9d857ac5f51598", "fullName": "scripts.test_login.TestLogin#test_login_001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "renxiaoyan"}, {"name": "thread", "value": "13196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}