{"name": "test_login_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x000001C295333520>\n\n    def test_login_002(self):\n>       assert 0\nE       assert 0\n\ntest_login.py:7: AssertionError"}, "start": 1694583631834, "stop": 1694583631834, "uuid": "5256af45-95f4-48fe-84ed-81ba4979052b", "historyId": "807d7923429a723b53f08fbc31059c73", "testCaseId": "807d7923429a723b53f08fbc31059c73", "fullName": "scripts.test_login.TestLogin#test_login_002", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "renxiaoyan"}, {"name": "thread", "value": "13196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}